#!/bin/bash

# FileVersion=6

tmpfile=/tmp/remove-with-same-subject

set -eu -o pipefail -o errtrace

declare subject email
declare -a subjectin=()

email="$(head -n300)"

readarray -t subjectin < <(echo "${email}" | grep -i -m1 -A5 "^Subject:" | sed 's/^Subject:\s*//I')

for (( i=0; i<${#subjectin[@]}; i++ )); do
	if [[ ${i} -eq 0 ]]; then
		subject+="${subjectin[$i]}"
	else
		[[ ${subjectin[$i]} =~ ^" " ]] && subject+="${subjectin[$i]}" || break
	fi
done

if [[ "${subject}" =~ ^=\?[uU][tT][fF]-8 ]]; then
	subjectnew="$(echo "${subject}" | ~/.mutt/bin/decode-subject.pl)"
	[[ ${#subjectnew} -eq 0 ]] || subject="${subjectnew}"
fi

subject="$(echo "${subject}" | sed -e 's/[~%+=<>|\^$\()"'\''*?\\[]/\./g' -e 's/^\s\+$//')"

if [[ ${#subject} -eq 0 ]]; then
	echo "<delete-message><next-new-then-unread>" > "${1}"
else
	echo "push \"<tag-pattern>\^${subject}<enter><tag-prefix><delete-message><next-new-then-unread>\"" > "${1}"
fi
# <sync-mailbox>
